/**
 * PDF Export Service
 * Phase 18: Professional Tools
 *
 * Generates professional PDF reports from analysis results
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File, Paths } from 'expo-file-system';
import { Platform } from 'react-native';
import { SavedAnalysis, Insight, HomeTip, RiskFlag } from '@/types/analysis';
import { format } from 'date-fns';
import { tr, enUS } from 'date-fns/locale';

export interface PdfConfig {
  clinicName?: string;
  clinicLogo?: string; // Base64 encoded
  clinicAddress?: string;
  clinicPhone?: string;
  professionalName?: string;
  professionalTitle?: string;
  includeRecommendations?: boolean;
  includeTips?: boolean;
  includeRiskFlags?: boolean;
  language?: 'tr' | 'en';
}

export interface ClientInfo {
  name: string;
  age?: number;
  gender?: 'male' | 'female';
  parentName?: string;
  sessionNumber?: number;
  notes?: string;
}

class PdfService {
  private static instance: PdfService;
  private config: PdfConfig = {
    language: 'tr',
    includeRecommendations: true,
    includeTips: true,
    includeRiskFlags: true,
  };

  private constructor() {}

  static getInstance(): PdfService {
    if (!PdfService.instance) {
      PdfService.instance = new PdfService();
    }
    return PdfService.instance;
  }

  setConfig(config: Partial<PdfConfig>): void {
    this.config = { ...this.config, ...config };
  }

  getConfig(): PdfConfig {
    return { ...this.config };
  }

  private getLocale() {
    return this.config.language === 'tr' ? tr : enUS;
  }

  private getTranslations() {
    const isTr = this.config.language === 'tr';
    return {
      reportTitle: isTr ? 'Çizim Analiz Raporu' : 'Drawing Analysis Report',
      clientInfo: isTr ? 'Danışan Bilgileri' : 'Client Information',
      name: isTr ? 'Ad' : 'Name',
      age: isTr ? 'Yaş' : 'Age',
      gender: isTr ? 'Cinsiyet' : 'Gender',
      male: isTr ? 'Erkek' : 'Male',
      female: isTr ? 'Kız' : 'Female',
      parent: isTr ? 'Ebeveyn' : 'Parent',
      session: isTr ? 'Seans' : 'Session',
      analysisDate: isTr ? 'Analiz Tarihi' : 'Analysis Date',
      testType: isTr ? 'Test Türü' : 'Test Type',
      confidence: isTr ? 'Güven Seviyesi' : 'Confidence Level',
      insights: isTr ? 'Bulgular' : 'Insights',
      evidence: isTr ? 'Kanıtlar' : 'Evidence',
      strength: isTr ? 'Güç' : 'Strength',
      weak: isTr ? 'Zayıf' : 'Weak',
      moderate: isTr ? 'Orta' : 'Moderate',
      strong: isTr ? 'Güçlü' : 'Strong',
      recommendations: isTr ? 'Ev Aktiviteleri' : 'Home Activities',
      steps: isTr ? 'Adımlar' : 'Steps',
      why: isTr ? 'Neden' : 'Why',
      riskFlags: isTr ? 'Dikkat Edilmesi Gerekenler' : 'Risk Flags',
      action: isTr ? 'Önerilen Aksiyon' : 'Recommended Action',
      clinicalNotes: isTr ? 'Klinik Notlar' : 'Clinical Notes',
      disclaimer: isTr
        ? 'Bu rapor profesyonel tanı yerine geçmez. Ciddi endişeler için bir uzmana danışınız.'
        : 'This report does not replace professional diagnosis. Consult a specialist for serious concerns.',
      generatedBy: isTr ? 'Oluşturan' : 'Generated by',
      page: isTr ? 'Sayfa' : 'Page',
      of: isTr ? '/' : 'of',
    };
  }

  private generateStyles(): string {
    return `
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
          font-size: 11pt;
          line-height: 1.5;
          color: #1F2937;
          padding: 40px;
        }

        .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          border-bottom: 2px solid #7C3AED;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }

        .clinic-info {
          flex: 1;
        }

        .clinic-name {
          font-size: 18pt;
          font-weight: bold;
          color: #7C3AED;
          margin-bottom: 4px;
        }

        .clinic-details {
          font-size: 9pt;
          color: #6B7280;
        }

        .report-title {
          text-align: right;
        }

        .report-title h1 {
          font-size: 16pt;
          color: #1F2937;
          margin-bottom: 4px;
        }

        .report-date {
          font-size: 10pt;
          color: #6B7280;
        }

        .section {
          margin-bottom: 25px;
          page-break-inside: avoid;
        }

        .section-title {
          font-size: 12pt;
          font-weight: bold;
          color: #7C3AED;
          margin-bottom: 12px;
          padding-bottom: 6px;
          border-bottom: 1px solid #E5E7EB;
        }

        .info-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 10px;
        }

        .info-item {
          display: flex;
          gap: 8px;
        }

        .info-label {
          font-weight: 600;
          color: #374151;
          min-width: 100px;
        }

        .info-value {
          color: #1F2937;
        }

        .insight-card {
          background: #F9FAFB;
          border-radius: 8px;
          padding: 16px;
          margin-bottom: 12px;
          border-left: 4px solid #7C3AED;
        }

        .insight-title {
          font-weight: 600;
          font-size: 11pt;
          color: #1F2937;
          margin-bottom: 6px;
        }

        .insight-summary {
          color: #4B5563;
          margin-bottom: 8px;
        }

        .insight-evidence {
          font-size: 9pt;
          color: #6B7280;
          padding-left: 16px;
        }

        .insight-evidence li {
          margin-bottom: 4px;
        }

        .strength-badge {
          display: inline-block;
          padding: 2px 8px;
          border-radius: 12px;
          font-size: 9pt;
          font-weight: 500;
        }

        .strength-weak {
          background: #FEF3C7;
          color: #92400E;
        }

        .strength-moderate {
          background: #DBEAFE;
          color: #1E40AF;
        }

        .strength-strong {
          background: #D1FAE5;
          color: #065F46;
        }

        .tip-card {
          background: #ECFDF5;
          border-radius: 8px;
          padding: 14px;
          margin-bottom: 10px;
        }

        .tip-title {
          font-weight: 600;
          color: #065F46;
          margin-bottom: 6px;
        }

        .tip-steps {
          font-size: 10pt;
          padding-left: 20px;
          color: #047857;
          margin-bottom: 6px;
        }

        .tip-why {
          font-size: 9pt;
          color: #6B7280;
          font-style: italic;
        }

        .risk-card {
          background: #FEF2F2;
          border-radius: 8px;
          padding: 14px;
          margin-bottom: 10px;
          border-left: 4px solid #EF4444;
        }

        .risk-type {
          font-weight: 600;
          color: #991B1B;
          margin-bottom: 4px;
        }

        .risk-summary {
          color: #7F1D1D;
          font-size: 10pt;
        }

        .notes-box {
          background: #FFFBEB;
          border: 1px dashed #F59E0B;
          border-radius: 8px;
          padding: 16px;
          min-height: 100px;
        }

        .notes-content {
          white-space: pre-wrap;
          color: #92400E;
          font-size: 10pt;
        }

        .disclaimer {
          margin-top: 30px;
          padding: 12px;
          background: #F3F4F6;
          border-radius: 6px;
          font-size: 9pt;
          color: #6B7280;
          text-align: center;
          font-style: italic;
        }

        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #E5E7EB;
          display: flex;
          justify-content: space-between;
          font-size: 9pt;
          color: #9CA3AF;
        }

        .signature-area {
          margin-top: 30px;
          display: flex;
          justify-content: flex-end;
        }

        .signature-box {
          width: 200px;
          text-align: center;
        }

        .signature-line {
          border-top: 1px solid #374151;
          margin-bottom: 6px;
        }

        .signature-name {
          font-size: 10pt;
          font-weight: 600;
          color: #1F2937;
        }

        .signature-title {
          font-size: 9pt;
          color: #6B7280;
        }

        @media print {
          body {
            padding: 20px;
          }
          .section {
            page-break-inside: avoid;
          }
        }
      </style>
    `;
  }

  private generateHeader(analysis: SavedAnalysis): string {
    const t = this.getTranslations();
    const formattedDate = format(new Date(analysis.createdAt), 'dd MMMM yyyy, HH:mm', {
      locale: this.getLocale(),
    });

    let clinicSection = '';
    if (this.config.clinicName) {
      clinicSection = `
        <div class="clinic-info">
          ${this.config.clinicLogo ? `<img src="${this.config.clinicLogo}" alt="Logo" style="height: 40px; margin-bottom: 8px;" />` : ''}
          <div class="clinic-name">${this.config.clinicName}</div>
          ${this.config.clinicAddress ? `<div class="clinic-details">${this.config.clinicAddress}</div>` : ''}
          ${this.config.clinicPhone ? `<div class="clinic-details">${this.config.clinicPhone}</div>` : ''}
        </div>
      `;
    }

    return `
      <div class="header">
        ${clinicSection}
        <div class="report-title">
          <h1>${t.reportTitle}</h1>
          <div class="report-date">${formattedDate}</div>
        </div>
      </div>
    `;
  }

  private generateClientSection(client: ClientInfo): string {
    const t = this.getTranslations();

    return `
      <div class="section">
        <div class="section-title">${t.clientInfo}</div>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">${t.name}:</span>
            <span class="info-value">${client.name}</span>
          </div>
          ${
            client.age
              ? `
            <div class="info-item">
              <span class="info-label">${t.age}:</span>
              <span class="info-value">${client.age}</span>
            </div>
          `
              : ''
          }
          ${
            client.gender
              ? `
            <div class="info-item">
              <span class="info-label">${t.gender}:</span>
              <span class="info-value">${client.gender === 'male' ? t.male : t.female}</span>
            </div>
          `
              : ''
          }
          ${
            client.parentName
              ? `
            <div class="info-item">
              <span class="info-label">${t.parent}:</span>
              <span class="info-value">${client.parentName}</span>
            </div>
          `
              : ''
          }
          ${
            client.sessionNumber
              ? `
            <div class="info-item">
              <span class="info-label">${t.session}:</span>
              <span class="info-value">#${client.sessionNumber}</span>
            </div>
          `
              : ''
          }
        </div>
      </div>
    `;
  }

  private generateAnalysisMetaSection(analysis: SavedAnalysis): string {
    const t = this.getTranslations();
    const meta = analysis.analysisResult.meta;

    return `
      <div class="section">
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">${t.testType}:</span>
            <span class="info-value">${meta.testType}</span>
          </div>
          <div class="info-item">
            <span class="info-label">${t.confidence}:</span>
            <span class="info-value">${Math.round(meta.confidence * 100)}%</span>
          </div>
        </div>
      </div>
    `;
  }

  private generateInsightsSection(insights: Insight[]): string {
    const t = this.getTranslations();

    const getStrengthClass = (strength: string) => {
      switch (strength) {
        case 'weak':
          return 'strength-weak';
        case 'moderate':
          return 'strength-moderate';
        case 'strong':
          return 'strength-strong';
        default:
          return 'strength-moderate';
      }
    };

    const getStrengthText = (strength: string) => {
      switch (strength) {
        case 'weak':
          return t.weak;
        case 'moderate':
          return t.moderate;
        case 'strong':
          return t.strong;
        default:
          return t.moderate;
      }
    };

    return `
      <div class="section">
        <div class="section-title">${t.insights}</div>
        ${insights
          .map(
            insight => `
          <div class="insight-card">
            <div style="display: flex; justify-content: space-between; align-items: flex-start;">
              <div class="insight-title">${insight.title}</div>
              <span class="strength-badge ${getStrengthClass(insight.strength)}">
                ${getStrengthText(insight.strength)}
              </span>
            </div>
            <div class="insight-summary">${insight.summary}</div>
            ${
              insight.evidence.length > 0
                ? `
              <div style="font-size: 9pt; color: #6B7280; margin-bottom: 4px;">${t.evidence}:</div>
              <ul class="insight-evidence">
                ${insight.evidence.map(e => `<li>${e}</li>`).join('')}
              </ul>
            `
                : ''
            }
          </div>
        `
          )
          .join('')}
      </div>
    `;
  }

  private generateTipsSection(tips: HomeTip[]): string {
    if (!this.config.includeTips || tips.length === 0) return '';

    const t = this.getTranslations();

    return `
      <div class="section">
        <div class="section-title">${t.recommendations}</div>
        ${tips
          .map(
            tip => `
          <div class="tip-card">
            <div class="tip-title">${tip.title}</div>
            <ol class="tip-steps">
              ${tip.steps.map(step => `<li>${step}</li>`).join('')}
            </ol>
            <div class="tip-why">${t.why}: ${tip.why}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `;
  }

  private generateRiskFlagsSection(flags: RiskFlag[]): string {
    if (!this.config.includeRiskFlags || flags.length === 0) return '';

    const t = this.getTranslations();

    const getRiskTypeText = (type: string) => {
      const labels: Record<string, { tr: string; en: string }> = {
        self_harm: { tr: 'Kendine Zarar', en: 'Self Harm' },
        harm_others: { tr: 'Başkalarına Zarar', en: 'Harm to Others' },
        sexual_inappropriate: { tr: 'Uygunsuz Cinsel İçerik', en: 'Sexual Content' },
        violence: { tr: 'Şiddet', en: 'Violence' },
        severe_distress: { tr: 'Ciddi Sıkıntı', en: 'Severe Distress' },
        trend_regression: { tr: 'Gerileme Eğilimi', en: 'Regression Trend' },
      };
      return labels[type]?.[this.config.language || 'tr'] || type;
    };

    return `
      <div class="section">
        <div class="section-title">${t.riskFlags}</div>
        ${flags
          .map(
            flag => `
          <div class="risk-card">
            <div class="risk-type">${getRiskTypeText(flag.type)}</div>
            <div class="risk-summary">${flag.summary}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `;
  }

  private generateNotesSection(notes?: string): string {
    if (!notes) return '';

    const t = this.getTranslations();

    return `
      <div class="section">
        <div class="section-title">${t.clinicalNotes}</div>
        <div class="notes-box">
          <div class="notes-content">${notes}</div>
        </div>
      </div>
    `;
  }

  private generateSignatureArea(): string {
    if (!this.config.professionalName) return '';

    return `
      <div class="signature-area">
        <div class="signature-box">
          <div class="signature-line"></div>
          <div class="signature-name">${this.config.professionalName}</div>
          ${this.config.professionalTitle ? `<div class="signature-title">${this.config.professionalTitle}</div>` : ''}
        </div>
      </div>
    `;
  }

  private generateFooter(): string {
    const t = this.getTranslations();

    return `
      <div class="disclaimer">${t.disclaimer}</div>
      <div class="footer">
        <div>${t.generatedBy}: Renkioo</div>
        <div>${format(new Date(), 'dd.MM.yyyy HH:mm')}</div>
      </div>
    `;
  }

  async generateAnalysisReport(
    analysis: SavedAnalysis,
    clientInfo: ClientInfo,
    additionalNotes?: string
  ): Promise<string> {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Analysis Report</title>
          ${this.generateStyles()}
        </head>
        <body>
          ${this.generateHeader(analysis)}
          ${this.generateClientSection(clientInfo)}
          ${this.generateAnalysisMetaSection(analysis)}
          ${this.generateInsightsSection(analysis.analysisResult.insights)}
          ${this.generateTipsSection(analysis.analysisResult.homeTips)}
          ${this.generateRiskFlagsSection(analysis.analysisResult.riskFlags)}
          ${this.generateNotesSection(additionalNotes || analysis.notes)}
          ${this.generateSignatureArea()}
          ${this.generateFooter()}
        </body>
      </html>
    `;

    return html;
  }

  async exportToPdf(
    analysis: SavedAnalysis,
    clientInfo: ClientInfo,
    additionalNotes?: string
  ): Promise<string> {
    try {
      const html = await this.generateAnalysisReport(analysis, clientInfo, additionalNotes);

      // Generate PDF
      const { uri } = await Print.printToFileAsync({
        html,
        base64: false,
      });

      // Create a proper filename
      const sanitizedName = clientInfo.name.replace(/[^a-zA-Z0-9]/g, '_');
      const dateStr = format(new Date(analysis.createdAt), 'yyyy-MM-dd');
      const newFileName = `Renkioo_Report_${sanitizedName}_${dateStr}.pdf`;

      // Move file to a better location with proper name
      const sourceFile = new File(uri);
      const destFile = new File(Paths.document, newFileName);
      await sourceFile.move(destFile);

      return destFile.uri;
    } catch (error) {
      console.error('PDF generation error:', error);
      throw new Error('PDF oluşturulurken hata oluştu');
    }
  }

  async sharePdf(pdfUri: string): Promise<void> {
    try {
      if (Platform.OS === 'web') {
        // For web, open in new tab
        window.open(pdfUri, '_blank');
        return;
      }

      const isAvailable = await Sharing.isAvailableAsync();
      if (!isAvailable) {
        throw new Error('Paylaşım bu cihazda desteklenmiyor');
      }

      await Sharing.shareAsync(pdfUri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Raporu Paylaş',
        UTI: 'com.adobe.pdf',
      });
    } catch (error) {
      console.error('Share error:', error);
      throw error;
    }
  }

  async printPdf(
    analysis: SavedAnalysis,
    clientInfo: ClientInfo,
    additionalNotes?: string
  ): Promise<void> {
    try {
      const html = await this.generateAnalysisReport(analysis, clientInfo, additionalNotes);
      await Print.printAsync({ html });
    } catch (error) {
      console.error('Print error:', error);
      throw new Error('Yazdırma sırasında hata oluştu');
    }
  }
}

export const pdfService = PdfService.getInstance();
export default PdfService;
